name: content-web

on:
  push:
    branches:
    - master
    paths:
    - 'content-web/**'
    workflow_dispatch:

env:
  imageRepository: 'content-web'
  resourceGroupName: 'fabmedical-w07'
  containerRegistryName: 'fabmedicalw07'
  containerRegistry: 'fabmedicalw07.azurecr.io'
  dockerfilePath: './content-web'
  tag: '${{ github.run_id }}'


jobs:
  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.containerRegistry }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
 
    - name: Build and push an image to container Registry
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.dockerfilePath }}
        file: "${{ env.dockerfilePath }}/Dockefile"
        pull: true
        push: true
        tags: |
          ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag }}
          ${{ env.containerRegistry }}/${{ env.imageRepository }}:latest





